# Generated by Django 4.1.5 on 2023-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.PositiveIntegerField()),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("o", "one time"),
                            ("d", "daily"),
                            ("w", "weekly"),
                            ("m", "monthly"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
